//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PH4_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PH4_WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 123456
        ///jesus
        ///password
        ///12345678
        ///christ
        ///love
        ///princess
        ///jesus1
        ///sunshine
        ///1234567
        ///blessed
        ///angel
        ///lovely
        ///mother
        ///iloveyou
        ///blessing
        ///angels
        ///7777777
        ///1234
        ///freedom
        ///single
        ///richard
        ///loving
        ///london
        ///favour
        ///12345
        ///mylove
        ///emmanuel
        ///shalom
        ///shadow
        ///grace
        ///123456ss
        ///1111
        ///spirit
        ///samuel
        ///pastor
        ///michael
        ///manner
        ///john316
        ///heaven
        ///football
        ///destiny
        ///computer
        ///tigger
        ///sunday
        ///samson
        ///maxwell
        ///looking
        ///junior
        ///joshua
        ///hope
        ///faithful
        ///faith
        ///church
        ///buster
        ///ashley
        ///7777
        ///wisdom
        ///solomon
        ///school
        ///redeemed
        ///rain [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0		Reserved
        ///1	tcpmux	TCP Port Service Multiplexer
        ///2	compressnet	Management Utility
        ///3	compressnet	Compression Process
        ///4	Unknown
        ///5	rje	Remote Job Entry
        ///6	Unknown
        ///7	echo	Echo (MS: : TCP/IP (SimpTcp))
        ///8	Unknown
        ///9	discard	Discard (MS: : TCP/IP (SimpTcp))
        ///10	Unknown
        ///11	systat	Active Users
        ///12	Unknown
        ///13	daytime	Daytime (RFC 867) (MS: : TCP/IP (SimpTcp))
        ///14	Unknown
        ///15	Unknown [was netstat]
        ///16	Unknown
        ///17	qotd	Quote of the Day (MS: : TCP/IP (SimpTcp))
        ///18	msp	Message Send Protocol
        ///19	chargen	Charact [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Ports {
            get {
                return ResourceManager.GetString("Ports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на tennis
        ///999999
        ///ncc1701
        ///coffee
        ///scooby
        ///0000
        ///miller
        ///boston
        ///q1w2e3r4
        ///fuckoff
        ///brandon
        ///yamaha
        ///chester
        ///mother
        ///forever
        ///johnny
        ///edward
        ///333333
        ///oliver
        ///redsox
        ///player
        ///nikita
        ///knight
        ///fender
        ///barney
        ///midnight
        ///please
        ///brandy
        ///chicago
        ///badboy
        ///iwantu
        ///slayer
        ///rangers
        ///charles
        ///angel
        ///flower
        ///bigdaddy
        ///rabbit
        ///wizard
        ///bigdick
        ///jasper
        ///enter
        ///rachel
        ///chris
        ///steven
        ///winner
        ///adidas
        ///victoria
        ///natasha
        ///1q2w3e4r
        ///jasmine
        ///winter
        ///prince
        ///panties
        ///marine
        ///ghbdtn
        ///fishing
        ///cocacola
        ///casper
        ///james
        ///232323
        ///raide [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string pwd {
            get {
                return ResourceManager.GetString("pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на www.test.ru	1
        ///www.kaylee-donley.us	40
        ///www.bookofluck.net	10
        ///c.securepaths.com	5
        ///pubportal.brkmd.com	3
        ///affiliate.icclicktracker.com	5
        ///ads4cheap.com	10
        ///xhwqginopocs.com	15
        ///ad81m.adk2.co	20
        ///208.185.87.118.liveadvert.com	5
        ///www.btxoeiisonxh.com	1
        ///slimxxxtubemue.dnset.com	15
        ///mediatraffic.com.ua	25
        ///bs.serving-sys.com.net	45
        ///fra373.ib.adnxs.com	52
        ///barbpool07.2cnt.net	60
        ///pix04-pd04.revsci.net	41
        ///adlook.net	35
        ///oekwa.voluumtrk.com	35
        ///www.cuelinks.com	25
        ///adserver.plhb.com	40
        ///polanders.com	45
        ///www.g [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
    }
}
